import assert from 'node:assert/strict';
import { IDBFactory } from 'fake-indexeddb';
import { LocalRepository, databaseName } from '../src/lib/storage';
import { initialDocument } from '../src/lib/lexicon';
const factory=new IDBFactory();const a=new LocalRepository(factory,'persistence-test');
const first=await a.load();assert.equal(first.revision,0);assert.equal(first.document.profiles.length,7);
const changed=structuredClone(first.document);changed.profiles[0].entries.unshift({id:'local-test',code:'jiemei',phrase:'离线媎妹',priority:1,enabled:true});
await a.save(changed,0);a.close();
const b=new LocalRepository(factory,'persistence-test');const reopened=await b.load();assert.equal(reopened.revision,1);assert.equal(reopened.document.profiles[0].entries[0].phrase,'离线媎妹');
await assert.rejects(()=>b.save(first.document,0),/另一个窗口/);
const invalid=structuredClone(changed);invalid.profiles[0].entries[0].priority=0;await assert.rejects(()=>b.save(invalid,1));assert.equal((await b.load()).revision,1);
const backup=JSON.parse(JSON.stringify(reopened.document));backup.profiles[0].entries=backup.profiles[0].entries.filter((e:{id:string})=>e.id!=='local-test');await b.save(backup,1);assert.equal((await b.load()).document.profiles[0].entries.some(e=>e.id==='local-test'),false);
const c=new LocalRepository(factory,'persistence-test');await c.load();const concurrent=await Promise.allSettled([b.save(changed,2),c.save(initialDocument(),2)]);assert.equal(concurrent.filter(r=>r.status==='fulfilled').length,1);assert.equal(concurrent.filter(r=>r.status==='rejected').length,1);
b.close();c.close();
const blocked=new LocalRepository({open(){throw new Error('blocked')}} as unknown as IDBFactory);
const temp=await blocked.load();assert.equal(blocked.mode,'memory');await blocked.save(changed,temp.revision);assert.equal((await blocked.load()).document.profiles[0].entries[0].id,'local-test');
const corruptDb=await new Promise<IDBDatabase>((resolve,reject)=>{const r=factory.open('corrupt',1);r.onupgradeneeded=()=>r.result.createObjectStore('workspace');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
await new Promise<void>((resolve,reject)=>{const tx=corruptDb.transaction('workspace','readwrite');tx.objectStore('workspace').put({version:999,important:'retain me'},'current');tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});corruptDb.close();
const corrupt=new LocalRepository(factory,'corrupt');await assert.rejects(()=>corrupt.load());assert.match(corrupt.recoveryText(),/retain me/);await corrupt.startTemporary();assert.equal(corrupt.mode,'memory');corrupt.close();
console.log('PASS: IndexedDB save/reopen, stale tabs, atomic competing saves, invalid input, backup restore, temporary mode and non-destructive corrupt-data recovery.');
const original=initialDocument();const manager=new LocalRepository(factory,'profile-management');await manager.load();
const reordered={profiles:[...original.profiles].reverse()};await manager.save(reordered,0);manager.close();
const managerReloaded=new LocalRepository(factory,'profile-management');assert.deepEqual((await managerReloaded.load()).document,reordered);
const removed={profiles:reordered.profiles.slice(1)};await managerReloaded.save(removed,1);assert.deepEqual((await managerReloaded.load()).document,removed);
await assert.rejects(()=>managerReloaded.save({profiles:[]},2));assert.deepEqual((await managerReloaded.load()).document,removed);
await managerReloaded.save(JSON.parse(JSON.stringify(original)),2);assert.deepEqual((await managerReloaded.load()).document,original);managerReloaded.close();
assert.equal(databaseName({protocol:'file:',href:'file:///any/folder/index.html'}),'sis-lexicon-offline-v1');
assert.equal(databaseName({protocol:'https:',href:'https://example.github.io/first/'}),databaseName({protocol:'https:',href:'https://example.github.io/first/index.html?version=2'}));
assert.notEqual(databaseName({protocol:'https:',href:'https://example.github.io/first/'}),databaseName({protocol:'https:',href:'https://example.github.io/second/'}));
console.log('PASS: scheme order/deletion persist and restore, last-scheme validation, legacy file storage, hosted project isolation.');
