import assert from 'node:assert/strict';
import { IDBFactory } from 'fake-indexeddb';
import { LocalRepository, databaseName } from '../src/lib/storage';
import { initialDocument } from '../src/lib/lexicon';
const factory=new IDBFactory();const a=new LocalRepository(factory,'persistence-test');
const first=await a.load();assert.equal(first.revision,0);assert.equal(first.document.profiles.length,7);
const changed=structuredClone(first.document);changed.profiles[0].entries.unshift({id:'local-test',code:'jiemei',phrase:'离线媎妹',priority:1,enabled:true});
await a.save(changed,0);a.close();
const b=new LocalRepository(factory,'persistence-test');const reopened=await b.load();assert.equal(reopened.revision,1);assert.equal(reopened.document.profiles[0].entries[0].phrase,'离线媎妹');
await assert.rejects(()=>b.save(first.document,0),/另一个窗口/);
const invalid=structuredClone(changed);invalid.profiles[0].entries[0].priority=0;await assert.rejects(()=>b.save(invalid,1));assert.equal((await b.load()).revision,1);
const backup=JSON.parse(JSON.stringify(reopened.document));backup.profiles[0].entries=backup.profiles[0].entries.filter((e:{id:string})=>e.id!=='local-test');await b.save(backup,1);assert.equal((await b.load()).document.profiles[0].entries.some(e=>e.id==='local-test'),false);
const c=new LocalRepository(factory,'persistence-test');await c.load();const concurrent=await Promise.allSettled([b.save(changed,2),c.save(initialDocument(),2)]);assert.equal(concurrent.filter(r=>r.status==='fulfilled').length,1);assert.equal(concurrent.filter(r=>r.status==='rejected').length,1);
b.close();c.close();
const blocked=new LocalRepository({open(){throw new Error('blocked')}} as unknown as IDBFactory);
const temp=await blocked.load();assert.equal(blocked.mode,'memory');await blocked.save(changed,temp.revision);assert.equal((await blocked.load()).document.profiles[0].entries[0].id,'local-test');
const corruptDb=await new Promise<IDBDatabase>((resolve,reject)=>{const r=factory.open('corrupt',1);r.onupgradeneeded=()=>r.result.createObjectStore('workspace');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
await new Promise<void>((resolve,reject)=>{const tx=corruptDb.transaction('workspace','readwrite');tx.objectStore('workspace').put({version:999,important:'retain me'},'current');tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});corruptDb.close();
const corrupt=new LocalRepository(factory,'corrupt');await assert.rejects(()=>corrupt.load());assert.match(corrupt.recoveryText(),/retain me/);await corrupt.startTemporary();assert.equal(corrupt.mode,'memory');corrupt.close();
console.log('PASS: IndexedDB save/reopen, stale tabs, atomic competing saves, invalid input, backup restore, temporary mode and non-destructive corrupt-data recovery.');
const original=initialDocument();const manager=new LocalRepository(factory,'profile-management');await manager.load();
const reordered={profiles:[...original.profiles].reverse()};await manager.save(reordered,0);manager.close();
const managerReloaded=new LocalRepository(factory,'profile-management');assert.deepEqual((await managerReloaded.load()).document,reordered);
const removed={profiles:reordered.profiles.slice(1)};await managerReloaded.save(removed,1);assert.deepEqual((await managerReloaded.load()).document,removed);
await assert.rejects(()=>managerReloaded.save({profiles:[]},2));assert.deepEqual((await managerReloaded.load()).document,removed);
await managerReloaded.save(JSON.parse(JSON.stringify(original)),2);assert.deepEqual((await managerReloaded.load()).document,original);managerReloaded.close();
assert.equal(databaseName({protocol:'file:',href:'file:///any/folder/index.html'}),'sis-lexicon-offline-v1');
assert.equal(databaseName({protocol:'https:',href:'https://example.github.io/first/'}),databaseName({protocol:'https:',href:'https://example.github.io/first/index.html?version=2'}));
assert.notEqual(databaseName({protocol:'https:',href:'https://example.github.io/first/'}),databaseName({protocol:'https:',href:'https://example.github.io/second/'}));
console.log('PASS: scheme order/deletion persist and restore, last-scheme validation, legacy file storage, hosted project isolation.');

// Clearing erases dictionary content, persists across reloads, and blocks stale writers.
const clearing=new LocalRepository(factory,'clear-test');const clearStart=await clearing.load();
const privateWords=structuredClone(clearStart.document);privateWords.profiles[0].entries.unshift({id:'erase-me',code:'eraseme',phrase:'待清除的测试词',priority:1,enabled:true});await clearing.save(privateWords,0);
const staleWriter=new LocalRepository(factory,'clear-test');await staleWriter.load();
const unrelated=new LocalRepository(factory,'unrelated-test');const unrelatedStart=await unrelated.load();
await assert.rejects(()=>clearing.clear(0),/另一个窗口/);assert.deepEqual((await clearing.load()).document,privateWords);
await clearing.clear(1);assert.equal(clearing.recoveryText(),'null');await assert.rejects(()=>clearing.load(),/已清除/);
const afterClear=new LocalRepository(factory,'clear-test');await assert.rejects(()=>afterClear.load(),/已清除/);
assert.deepEqual((await unrelated.load()).document,unrelatedStart.document);
const inspect=await new Promise<IDBDatabase>((resolve,reject)=>{const r=factory.open('clear-test');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
const marker=await new Promise<unknown>((resolve,reject)=>{const r=inspect.transaction('workspace').objectStore('workspace').get('current');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
assert.deepEqual(marker,{version:1,cleared:true,revision:2});inspect.close();
await assert.rejects(()=>staleWriter.save(privateWords,1),/已清除/);
await afterClear.restart();const restarted=await afterClear.load();assert.deepEqual(restarted.document,initialDocument());assert.equal(restarted.revision,3);
await assert.rejects(()=>staleWriter.save(privateWords,1),/另一个窗口/);await afterClear.save(privateWords,3);assert.deepEqual((await afterClear.load()).document,privateWords);
clearing.close();staleWriter.close();afterClear.close();unrelated.close();
const tempClear=new LocalRepository({open(){throw Error('unavailable');}} as unknown as IDBFactory);await tempClear.load();await tempClear.clear(0);await assert.rejects(()=>tempClear.load(),/已清除/);await assert.rejects(()=>tempClear.save(initialDocument(),0),/已清除/);await tempClear.restart();assert.equal((await tempClear.load()).revision,2);
console.log('PASS: clear erases word content, leaves only a revision marker, survives reload, preserves other stores, rejects stale deletion/writes and supports explicit restart/restore; temporary mode clear.');
const failureRepo=new LocalRepository(factory,'clear-failure');const beforeFailure=await failureRepo.load();
const {IDBObjectStore}=await import('fake-indexeddb');const put=IDBObjectStore.prototype.put;
IDBObjectStore.prototype.put=function(value:unknown,key?:IDBValidKey){if((value as {cleared?:boolean})?.cleared)throw new Error('simulated write failure');return put.call(this,value,key);};
try{await assert.rejects(()=>failureRepo.clear(beforeFailure.revision),/simulated write failure/);}finally{IDBObjectStore.prototype.put=put;}
assert.deepEqual((await failureRepo.load()).document,beforeFailure.document);failureRepo.close();
console.log('PASS: aborted clear leaves the original dictionary intact.');
