'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { flushSync } from 'react-dom';
import { ArrowDown, ArrowUp, ArrowUpRight, ChevronLeft, ChevronRight, CircleHelp, HardDrive, Download, FileUp, Flower2, Loader2, Pencil, Plus, Search, ShieldCheck, SlidersHorizontal, Trash2, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Checkbox } from '@/components/ui/checkbox';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from '@/components/ui/dialog';
import { AlertDialog, AlertDialogContent, AlertDialogHeader, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogAction, AlertDialogCancel } from '@/components/ui/alert-dialog';
import { Select, SelectTrigger, SelectContent, SelectItem, SelectValue } from '@/components/ui/select';
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from '@/components/ui/table';
import { Toaster, toast } from 'sonner';
import { documentSchema, entrySchema, Entry, Format, formats, Lexicon, ordered, Profile } from '@/lib/lexicon';
import { exportPackage, guides, planExport } from '@/lib/export';
import { repository, databaseName, DataClearedError } from '@/lib/storage';
import { HelpContent } from '@/components/HelpContent';
import { ProfileList } from '@/components/ProfileList';

type Editor={id?:string;code:string;phrase:string;priority:number;enabled:boolean};
function download(data:Uint8Array|string,name:string,type='application/octet-stream') {const b=typeof data==='string'?data:Uint8Array.from(data);const url=URL.createObjectURL(new Blob([b],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
const err=(e:unknown)=>e instanceof Error?e.message:'操作失败，请重试。';
export default function Home() {
 const [doc,setDoc]=useState<Lexicon|null>(null),[revision,setRevision]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[updated,setUpdated]=useState(''),[storageMode,setStorageMode]=useState<'local'|'memory'>('local');
 const [active,setActive]=useState('full'),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[page,setPage]=useState(0),[selected,setSelected]=useState<string[]>([]),[focusCode,setFocusCode]=useState('fumu');
 const [editor,setEditor]=useState<Editor|null>(null),[formError,setFormError]=useState(''),[deleting,setDeleting]=useState<string[]>([]),[exportOpen,setExportOpen]=useState(false),[target,setTarget]=useState<Format>('sogou'),[exportScope,setExportScope]=useState('all');
 const [help,setHelp]=useState(false),[createOpen,setCreateOpen]=useState(false),[newName,setNewName]=useState(''),[importOpen,setImportOpen]=useState(false),[bulk,setBulk]=useState(''),[restoring,setRestoring]=useState<Lexicon|null>(null);
 const [deletingProfile,setDeletingProfile]=useState<string|null>(null);
 const [cleared,setCleared]=useState(false),[clearOpen,setClearOpen]=useState(false);const clearChannel=useRef<BroadcastChannel|null>(null);
 const backupInput=useRef<HTMLInputElement>(null);const state=useRef({doc,revision,active,busy});state.current={doc,revision,active,busy};const lock=useRef(false);
 const profile=doc?.profiles.find(p=>p.id===active)||doc?.profiles[0];
 async function load(){setError('');try{const data=await repository.load();setDoc(data.document);setRevision(data.revision);setUpdated(data.updatedAt);setStorageMode(repository.mode);setCleared(false);}catch(e){if(e instanceof DataClearedError)finishClear();else setError(err(e));}}
 function finishClear(){setDoc(null);setCleared(true);setClearOpen(false);setHelp(false);setEditor(null);setBulk('');setRestoring(null);setSelected([]);setQuery('');setFocusCode('');setUpdated('');setDeleting([]);setDeletingProfile(null);setImportOpen(false);setExportOpen(false);setCreateOpen(false);setNewName('');setFormError('');setError('');}
 useEffect(()=>{void load();if(typeof BroadcastChannel==='undefined')return;const channel=new BroadcastChannel(databaseName());clearChannel.current=channel;channel.onmessage=event=>{if(event.data==='cleared')finishClear();};return()=>{channel.close();clearChannel.current=null;};},[]);
 async function clearData(){if(lock.current)return;lock.current=true;setBusy(true);try{await repository.clear(state.current.revision);finishClear();clearChannel.current?.postMessage('cleared');}catch(e){if(e instanceof DataClearedError)finishClear();else toast.error(err(e));}finally{lock.current=false;setBusy(false);}}

 useEffect(()=>{if(storageMode!=='memory'||cleared)return;const handler=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler);},[storageMode,cleared]);
 async function commit(next:Lexicon){if(lock.current)throw new Error('正在保存，请稍后再试。');const valid=documentSchema.parse(next);lock.current=true;setBusy(true);try{const result=await repository.save(valid,state.current.revision);flushSync(()=>{setDoc(valid);setRevision(result.revision);setUpdated(result.updatedAt);});return valid;}finally{lock.current=false;setBusy(false);}}
 async function changeEntries(entries:Entry[]){const current=state.current.doc;if(!current||!profile)return;await commit({...current,profiles:current.profiles.map(p=>p.id===profile.id?{...p,entries}:p)});}
 async function safe(action:()=>Promise<unknown>){try{await action();}catch(e){if(e instanceof DataClearedError)finishClear();else toast.error(err(e));}}
 function switchProfile(p:Profile){setActive(p.id);setQuery('');setFilter('all');setPage(0);setSelected([]);setTarget(p.format);setFocusCode(p.entries.find(e=>e.code==='fumu')?.code||p.entries[0]?.code||'');}
 async function moveProfile(id:string,target:string,after:boolean){const current=state.current.doc;if(!current)return;const item=current.profiles.find(p=>p.id===id);if(!item||id===target)return;const profiles=current.profiles.filter(p=>p.id!==id);const index=profiles.findIndex(p=>p.id===target);if(index<0)return;profiles.splice(index+(after?1:0),0,item);if(profiles.every((p,i)=>p.id===current.profiles[i].id))return;await commit({...current,profiles});toast.success('词库顺序已保存');}
 async function removeProfile(){const current=state.current.doc;if(!current||!deletingProfile)return;if(current.profiles.length<2)throw new Error('至少保留一个词库方案。');const index=current.profiles.findIndex(p=>p.id===deletingProfile);if(index<0)return;const shown=current.profiles.find(p=>p.id===state.current.active)||current.profiles[0];const profiles=current.profiles.filter(p=>p.id!==deletingProfile);await commit({...current,profiles});if(shown.id===deletingProfile)switchProfile(profiles[Math.min(index,profiles.length-1)]);setDeletingProfile(null);toast.success('词库方案已删除');}
 const counts=useMemo(()=>{const m=new Map<string,number>();profile?.entries.forEach(e=>{if(e.code)m.set(e.code,(m.get(e.code)||0)+1);});return m;},[profile]);
 const visible=useMemo(()=>profile?.entries.filter(e=>(!query||e.code.includes(query.toLowerCase())||e.phrase.includes(query))&&(filter==='all'||filter==='on'&&e.enabled||filter==='off'&&!e.enabled||filter==='shared'&&(counts.get(e.code)||0)>1))||[],[profile,query,filter,counts]);
 const candidates=ordered(profile?.entries.filter(e=>e.code===focusCode&&e.code)||[]);
 const pageCount=Math.max(1,Math.ceil(visible.length/30));const currentPage=Math.min(page,pageCount-1);const rows=visible.slice(currentPage*30,(currentPage+1)*30);
 const exportedProfile=profile?{...profile,entries:exportScope==='selected'?profile.entries.filter(e=>selected.includes(e.id)):profile.entries}:null;
 const plan=exportedProfile?planExport(exportedProfile,target):null;
 useEffect(()=>{setPage(0);},[query,filter]);
 function edit(e?:Entry){setEditor(e?{...e}:{code:'',phrase:'',priority:1,enabled:true});setFormError('');}
 async function saveEditor(){if(!editor||!profile)return;setFormError('');try{const entry=entrySchema.parse({...editor,id:editor.id||crypto.randomUUID(),code:editor.code.trim(),phrase:editor.phrase.trim()});await changeEntries(editor.id?profile.entries.map(e=>e.id===editor.id?entry:e):[entry,...profile.entries]);setFocusCode(entry.code);setEditor(null);toast.success(editor.id?'词条已更新':'词条已添加');}catch(e){setFormError(e instanceof Error&&e.name==='ZodError'?'请检查输入码、词条和优先级；同一输入码下不能重复添加相同词条。':err(e));}}
 async function move(id:string,direction:number){if(!profile)return;const list=[...candidates];const i=list.findIndex(e=>e.id===id),j=i+direction;if(j<0||j>=list.length)return;[list[i],list[j]]=[list[j],list[i]];const ranks=new Map(list.map((e,i)=>[e.id,i+1]));await changeEntries(profile.entries.map(e=>ranks.has(e.id)?{...e,priority:ranks.get(e.id)!}:e));}
 function backup(){if(doc)download(JSON.stringify({version:1,...doc},null,2),'词库-完整备份.json','application/json');}
 async function importBackup(file:File){try{if(file.size>1800000)throw new Error('文件过大，请选择本站导出的词库备份。');const obj=JSON.parse(await file.text());const parsed=documentSchema.parse(obj);setRestoring(parsed);}catch{toast.error('备份格式无效。请选择本站导出的 JSON 备份文件。');}}
 async function importLines(){if(!profile)return;setFormError('');try{const lines=bulk.split(/\r?\n/).filter(l=>l.trim());if(!lines.length)throw new Error('请先粘贴词条。');const entries=lines.map((l,i)=>{const cols=l.split('\t');if(cols.length<2||cols.length>3)throw new Error(`第 ${i+1} 行：输入码与词条之间请用 Tab 分隔。`);return entrySchema.parse({id:crypto.randomUUID(),code:cols[0].trim(),phrase:cols[1].trim(),priority:cols[2]?Number(cols[2]):1,enabled:true});});const existing=new Set(profile.entries.map(e=>JSON.stringify([e.code,e.phrase])));const added=entries.filter(e=>{const key=JSON.stringify([e.code,e.phrase]);if(existing.has(key))return false;existing.add(key);return true;});if(!added.length)throw new Error('所有词条已存在，无需重复导入。');await changeEntries([...added,...profile.entries]);setImportOpen(false);setBulk('');toast.success(`已添加 ${added.length} 条，跳过 ${entries.length-added.length} 条重复项`);}catch(e){setFormError(err(e));}}
 if(cleared)return <main className="loading-screen cleared-screen"><span className="brand-mark"><ShieldCheck size={28}/></span><h1>词库数据已清除</h1><p>{storageMode==='memory'?'当前临时会话已清空。':'此处保存的方案、词条及排序已清除。'}</p><p>可以关闭此页面，并删除本地使用包文件夹。</p><Button disabled={busy} onClick={()=>{setBusy(true);void repository.restart().then(load).catch(e=>setError(err(e))).finally(()=>setBusy(false));}}>重新打开默认词库</Button>{error&&<p role="alert">{error}</p>}</main>;
 if(!doc)return <main className="loading-screen"><span className="brand-mark"><Flower2 size={28}/></span><h1>多平台输入法自定义词库导出器</h1>{error?<><p role="alert">{error}</p><Button onClick={load}>重新载入</Button><Button variant="outline" onClick={()=>download(repository.recoveryText(),'词库恢复数据.json','application/json')}>下载原始保存数据</Button><Button variant="outline" onClick={()=>void repository.startTemporary().then(()=>load())}>在临时会话中打开默认词库</Button></>:<><Loader2 className="animate-spin"/><p>正在载入词库…</p></>}</main>;
 if(!profile)return null;
 const duplicateGroups=[...counts.values()].filter(n=>n>1).length;
 return <div className="workspace"><Toaster position="top-center" richColors/><aside className="sidebar"><div className="brand"><span className="brand-mark"><Flower2 size={25}/></span><div className="brand-title"><span>多平台输入法</span><span>自定义词库导出器</span></div></div><div className="side-label">词库方案 <span>{doc.profiles.length} 个</span></div><ProfileList profiles={doc.profiles} active={profile.id} disabled={busy||!!deletingProfile} onSelect={switchProfile} onMove={(id,target,after)=>void safe(()=>moveProfile(id,target,after))} onDelete={setDeletingProfile}/><button className="new-library" onClick={()=>{setNewName('');setCreateOpen(true);}}><Plus size={16}/> 新建词库</button><div className="side-bottom"><div className="private-note"><ShieldCheck size={17}/><div>本地保存 · 词库不上传</div></div><button onClick={()=>setHelp(true)}><CircleHelp size={17}/> 使用指南 <ArrowUpRight size={15}/></button></div></aside>
 <main className="main"><header className="topbar"><div className="breadcrumb">词库管理</div><div className="save-status" aria-live="polite">{busy?<Loader2 size={15} className="animate-spin"/>:<HardDrive size={15}/>}<span>{busy?'正在保存…':storageMode==='local'?'已保存到本机':'临时会话，请下载备份'}</span></div></header>
 <div className="content">{storageMode==='memory'&&<div className="storage-warning" role="alert">浏览器未能开启本地存储。当前修改仅保留到本次会话结束，请及时下载完整备份。</div>}<section className="heading-row"><div><h1>{profile.name}</h1><p>{profile.description}</p></div><div className="heading-actions"><Button variant="outline" onClick={backup}>备份 JSON</Button><Button variant="outline" onClick={()=>{setImportOpen(true);setFormError('');}}><FileUp size={16}/> 批量添加</Button><Button onClick={()=>{setExportScope(selected.length?'selected':'all');setExportOpen(true);}}><Download size={16}/> 导出输入法包</Button></div></section>
 <section className="stats"><div><span title="同一词语的不同输入码分别计数">记录数</span><strong>{profile.entries.length.toLocaleString()}<small>条</small></strong></div><div><span>词语数</span><strong>{new Set(profile.entries.map(e=>e.phrase)).size}</strong></div><div><span>已启用</span><strong>{profile.entries.filter(e=>e.enabled).length.toLocaleString()}</strong></div><div><span>同码候选组</span><strong>{duplicateGroups}</strong></div></section>
 <div className="editor-grid"><section className="lexicon-panel"><div className="panel-title"><h2>词条管理 <span>{visible.length}</span></h2><Button size="sm" onClick={()=>edit()} disabled={busy}><Plus size={16}/> 新增词条</Button></div><div className="toolbar"><div className="search"><Search size={17}/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索词条或输入码，如「母父」" aria-label="搜索词条"/>{query&&<button aria-label="清空搜索" onClick={()=>setQuery('')}><X size={14}/></button>}</div><Select value={filter} onValueChange={setFilter}><SelectTrigger className="filter-select" aria-label="筛选词条"><SlidersHorizontal size={14}/><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">全部词条</SelectItem><SelectItem value="on">已启用</SelectItem><SelectItem value="off">已停用</SelectItem><SelectItem value="shared">同码多候选</SelectItem></SelectContent></Select></div>
 {selected.length>0&&<div className="selection-bar"><span>已选 {selected.length} 条</span><button disabled={busy} onClick={()=>safe(()=>changeEntries(profile.entries.map(e=>selected.includes(e.id)?{...e,enabled:true}:e)))}>启用</button><button disabled={busy} onClick={()=>safe(()=>changeEntries(profile.entries.map(e=>selected.includes(e.id)?{...e,enabled:false}:e)))}>停用</button><button disabled={busy} onClick={()=>setDeleting(selected)}>删除</button><button onClick={()=>setSelected([])}>取消选择</button></div>}
 <Table><TableHeader><TableRow><TableHead className="check-col"><Checkbox aria-label="选择本页词条" checked={rows.length>0&&rows.every(e=>selected.includes(e.id))} onCheckedChange={v=>setSelected(v?[...new Set([...selected,...rows.map(e=>e.id)])]:selected.filter(id=>!rows.some(e=>e.id===id)))}/></TableHead><TableHead>词条</TableHead><TableHead>输入码</TableHead><TableHead className="rank-col">优先级</TableHead><TableHead>启用</TableHead><TableHead className="action-col"><span className="sr-only">操作</span></TableHead></TableRow></TableHeader><TableBody>{rows.map(e=><TableRow key={e.id} className={e.code&&e.code===focusCode?'focused-row':''} onClick={()=>setFocusCode(e.code)}><TableCell onClick={ev=>ev.stopPropagation()}><Checkbox aria-label={`选择 ${e.phrase}`} checked={selected.includes(e.id)} onCheckedChange={v=>setSelected(v?[...selected,e.id]:selected.filter(id=>id!==e.id))}/></TableCell><TableCell className={'phrase-cell '+(!e.enabled?'disabled-phrase':'')}><button onClick={()=>edit(e)}>{e.phrase}</button></TableCell><TableCell><button className="code" onClick={()=>setFocusCode(e.code)}>{e.code||'未设置'}</button></TableCell><TableCell><span className={'rank '+(e.priority===1?'first':'')}>{e.priority.toString().padStart(2,'0')}</span></TableCell><TableCell onClick={ev=>ev.stopPropagation()}><Checkbox aria-label={`启用 ${e.phrase}`} checked={e.enabled} disabled={busy} onCheckedChange={v=>safe(()=>changeEntries(profile.entries.map(x=>x.id===e.id?{...x,enabled:!!v}:x)))}/></TableCell><TableCell><div className="row-actions"><button aria-label={`编辑 ${e.phrase}`} disabled={busy} onClick={()=>edit(e)}><Pencil size={14}/></button><button aria-label={`删除 ${e.phrase}`} disabled={busy} onClick={()=>setDeleting([e.id])}><Trash2 size={14}/></button></div></TableCell></TableRow>)}</TableBody></Table>
 {!rows.length&&<div className="empty-state"><Search size={30}/><h3>{query?'没有找到这个词条':'这里还没有词条'}</h3><Button variant="outline" onClick={()=>edit()}>新增词条</Button></div>}
 <div className="pagination"><span>{visible.length?currentPage*30+1:0}–{Math.min((currentPage+1)*30,visible.length)} / {visible.length} 条</span><div><Button aria-label="上一页" variant="ghost" size="icon" disabled={currentPage===0} onClick={()=>setPage(currentPage-1)}><ChevronLeft size={16}/></Button><span>{currentPage+1} / {pageCount}</span><Button aria-label="下一页" variant="ghost" size="icon" disabled={currentPage+1>=pageCount} onClick={()=>setPage(currentPage+1)}><ChevronRight size={16}/></Button></div></div></section>
 <aside className="inspector"><h2 className="inspector-title">同码候选顺序</h2><p className="inspector-intro">数字越小，优先级越高。</p><label className="field-label" htmlFor="preview-code">输入码</label><div className="preview-input"><Input id="preview-code" value={focusCode} onChange={e=>setFocusCode(e.target.value.toLowerCase())} placeholder="例如 fumu"/></div><div className="candidate-list">{candidates.length?candidates.map((e,i)=><div className={'candidate '+(!e.enabled?'muted-candidate':'')} key={e.id}><span className={'candidate-number '+(i===0?'leading':'')}>{e.priority}</span><span>{e.phrase}{!e.enabled&&<small>已停用</small>}</span><div><button aria-label={`上移 ${e.phrase}`} disabled={busy||i===0} onClick={()=>safe(()=>move(e.id,-1))}><ArrowUp size={14}/></button><button aria-label={`下移 ${e.phrase}`} disabled={busy||i===candidates.length-1} onClick={()=>safe(()=>move(e.id,1))}><ArrowDown size={14}/></button></div></div>):<p className="no-candidates">{focusCode?'这个输入码还没有词条。':'输入一个码，查看候选。'}</p>}</div><div className="hint"><CircleHelp size={15}/><p>上下移动后，本组按 1、2、3… 重新排序。</p></div><div className="inspector-divider"/><button className="text-action" onClick={backup}>下载完整词库备份 <ArrowUpRight size={15}/></button></aside></div>
 </div></main>
 <Dialog open={!!editor} onOpenChange={open=>{if(!open&&!busy)setEditor(null);}}><DialogContent><DialogHeader><DialogTitle>{editor?.id?'编辑词条':'新增词条'}</DialogTitle><DialogDescription>词库：{profile.name}</DialogDescription></DialogHeader>{editor&&<form onSubmit={e=>{e.preventDefault();void saveEditor();}} className="form-stack"><label>词条<Input autoFocus value={editor.phrase} onChange={e=>setEditor({...editor,phrase:e.target.value})} placeholder="例如：媎妹" maxLength={500} required/></label><label>输入码<Input value={editor.code} onChange={e=>setEditor({...editor,code:e.target.value.toLowerCase()})} placeholder="例如：jiemei" maxLength={100}/><small>小写字母或数字。讯飞用户词可留空；其他格式导出时会检查输入码。</small></label><label>优先级<Input type="number" min={1} max={99} value={editor.priority} onChange={e=>setEditor({...editor,priority:Number(e.target.value)})}/><small>数字越小越优先。电脑输入法通常使用第 1–9 位。</small></label><label className="checkbox-label"><Checkbox checked={editor.enabled} onCheckedChange={v=>setEditor({...editor,enabled:!!v})}/> 启用，参与导出</label>{formError&&<p className="form-error" role="alert">{formError}</p>}<DialogFooter><Button type="button" variant="outline" onClick={()=>setEditor(null)} disabled={busy}>取消</Button><Button type="submit" disabled={busy}>{busy?'保存中…':'保存词条'}</Button></DialogFooter></form>}</DialogContent></Dialog>
 <AlertDialog open={deleting.length>0} onOpenChange={open=>{if(!open&&!busy)setDeleting([]);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>删除这 {deleting.length} 条词条？</AlertDialogTitle><AlertDialogDescription>它们将从当前词库中移除。若只是暂时不用，可以取消后选择停用。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>取消</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();void safe(async()=>{await changeEntries(profile.entries.filter(x=>!deleting.includes(x.id)));setSelected(selected.filter(id=>!deleting.includes(id)));setDeleting([]);toast.success('词条已删除');});}}>确认删除</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <AlertDialog open={!!deletingProfile} onOpenChange={open=>{if(!open&&!busy)setDeletingProfile(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>删除词库「{doc.profiles.find(p=>p.id===deletingProfile)?.name}」？</AlertDialogTitle><AlertDialogDescription>将删除这个方案及其中的 {doc.profiles.find(p=>p.id===deletingProfile)?.entries.length} 条记录，其他方案不受影响。删除后可通过之前下载的 JSON 备份恢复。</AlertDialogDescription></AlertDialogHeader><button className="text-action" onClick={backup}>先下载完整备份</button><AlertDialogFooter><AlertDialogCancel disabled={busy}>取消</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();void safe(removeProfile);}}>删除整个词库</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <Dialog open={exportOpen} onOpenChange={setExportOpen}><DialogContent className="export-dialog"><DialogHeader><DialogTitle>导出输入法包</DialogTitle><DialogDescription>选择目标输入法，检查兼容性后下载。</DialogDescription></DialogHeader><div className="form-stack"><label>目标输入法<Select value={target} onValueChange={v=>setTarget(v as Format)}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(formats).map(([id,name])=><SelectItem value={id} key={id}>{name}</SelectItem>)}</SelectContent></Select></label><label>导出范围<Select value={exportScope} onValueChange={setExportScope}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">当前词库的启用词条</SelectItem><SelectItem value="selected" disabled={!selected.length}>选中词条中的启用项（已选 {selected.length} 条）</SelectItem></SelectContent></Select></label><div className="export-summary"><div><strong>{plan?.entries.length}</strong><span>可导出</span></div><div><strong>{plan?.excluded.length}</strong><span>需另行处理</span></div><span>ZIP 内含输入法文件<br/>导入说明 · 词库备份</span></div><div className="export-notes">{plan?.notes.map(n=><p key={n}>{n}</p>)}</div>{!!plan?.excluded.length&&<details className="exclusions"><summary>查看未导出的 {plan.excluded.length} 条</summary><div>{plan.excluded.map(({entry,reason},i)=><p key={i}><b>{entry.phrase}</b> <code>{entry.code}</code><br/><span>{reason}</span></p>)}</div></details>}<p className="guide-text">{guides[target]}</p><DialogFooter><Button variant="outline" onClick={()=>setExportOpen(false)}>返回编辑</Button><Button disabled={!plan?.entries.length||busy} onClick={()=>{try{download(exportPackage(exportedProfile!,target),`词库-${profile.name}-${target}.zip`,'application/zip');toast.success('输入法包已生成，请查看浏览器下载');}catch(e){toast.error(err(e));}}}><Download size={16}/> 下载输入法包</Button></DialogFooter></div></DialogContent></Dialog>
 <Dialog open={createOpen} onOpenChange={setCreateOpen}><DialogContent><DialogHeader><DialogTitle>新建词库</DialogTitle><DialogDescription>创建一个空白词库。</DialogDescription></DialogHeader><form className="form-stack" onSubmit={e=>{e.preventDefault();void safe(async()=>{const p:Profile={id:crypto.randomUUID(),name:newName.trim(),description:'自定义词库',format:'sogou',entries:[]};await commit({...doc,profiles:[...doc.profiles,p]});switchProfile(p);setCreateOpen(false);});}}><label>词库名称<Input value={newName} onChange={e=>setNewName(e.target.value)} maxLength={40} required placeholder="例如：日常表达"/></label><DialogFooter><Button disabled={busy||!newName.trim()||doc.profiles.length>=20}>创建词库</Button></DialogFooter></form></DialogContent></Dialog>
 <Dialog open={importOpen} onOpenChange={setImportOpen}><DialogContent><DialogHeader><DialogTitle>批量添加词条</DialogTitle><DialogDescription>可从表格复制两列或三列：输入码、词条、优先级。</DialogDescription></DialogHeader><div className="form-stack"><label>每行一条，列之间以 Tab 分隔<textarea value={bulk} onChange={e=>setBulk(e.target.value)} placeholder={'jiemei\t媎妹\t1\njiemei\t姐妹\t2'} rows={8}/></label><small>省略优先级时设为 1；相同输入码与词条会跳过。此次添加只影响当前词库。</small>{formError&&<p className="form-error" role="alert">{formError}</p>}<DialogFooter><Button variant="outline" onClick={()=>backupInput.current?.click()}>从 JSON 备份恢复</Button><Button disabled={busy||!bulk.trim()} onClick={()=>void importLines()}>添加到当前词库</Button></DialogFooter></div></DialogContent></Dialog>
 <input type="file" accept=".json,application/json" ref={backupInput} hidden onChange={e=>{const file=e.target.files?.[0];if(file)void importBackup(file);e.target.value='';}}/>
 <AlertDialog open={!!restoring} onOpenChange={open=>{if(!open)setRestoring(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>用备份替换全部词库？</AlertDialogTitle><AlertDialogDescription>备份包含 {restoring?.profiles.length} 个词库、{restoring?.profiles.reduce((n,p)=>n+p.entries.length,0)} 条词条。恢复将替换当前全部词库，建议先下载当前备份。</AlertDialogDescription></AlertDialogHeader><button className="text-action" onClick={backup}>下载当前完整备份</button><AlertDialogFooter><AlertDialogCancel disabled={busy}>取消</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();void safe(async()=>{if(restoring){await commit(restoring);switchProfile(restoring.profiles[0]);setRestoring(null);setImportOpen(false);toast.success('词库已恢复');}});}}>替换并恢复</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <Dialog open={help} onOpenChange={setHelp}><DialogContent className="help-dialog"><DialogHeader><DialogTitle>使用指南</DialogTitle><DialogDescription>使用、数量、来源和数据清理。</DialogDescription></DialogHeader><HelpContent onBackup={backup} onClear={()=>{setHelp(false);setClearOpen(true);}} busy={busy} mode={storageMode} updated={updated}/></DialogContent></Dialog>
 <AlertDialog open={clearOpen} onOpenChange={open=>{if(!open&&!busy)setClearOpen(false);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>清除全部词库数据？</AlertDialogTitle><AlertDialogDescription>将清除 {doc.profiles.length} 个方案及其中的 {doc.profiles.reduce((n,p)=>n+p.entries.length,0)} 条记录，包括自定义修改与排序。清除后只能通过已下载的备份恢复。{storageMode==='memory'?'本次仅清除临时会话。':'此操作作用于当前页面使用的词库存储。'}</AlertDialogDescription></AlertDialogHeader><button className="text-action" onClick={backup} disabled={busy}>先下载完整备份</button><AlertDialogFooter><AlertDialogCancel disabled={busy}>取消</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={event=>{event.preventDefault();void clearData();}}>确认清除全部数据</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>;
}
